---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian-stretch
    image: debian:stretch
  #- name: debian-wheezy  # broken kernel
    #image: debian:wheezy
  - name: debian-jessie
    image: debian:jessie
  - name: ubuntu-xenial
    image: ubuntu:xenial
  - name: ubuntu-trusty
    image: ubuntu:trusty
  - name: ubuntu-precise
    image: ubuntu:precise
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: 'None'
